development:
  database: wikiful_development
  adapter: postgresql
  host: localhost
  port: 5432

test:
  database: wikiful_test
  adapter: postgresql
  host: localhost
  port: 5432

staging:
  database: wikiful
  adapter: postgresql
  host: localhost
  port: 5432

production:
  database: wikiful
  adapter: postgresql
  host: localhost
  port: 5432